# GC50 Website Trial

title: GC50 Virtual Sport Challenge (Trial)
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  GC50 Virtual Sport Challenge
baseurl: "/gc50_trial" # the subpath of your site, e.g. /blog
url: "https://chrischow.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  chrischow
github_repo: gc50_trial

plugins:
- jekyll-feed

sass:
    sass_dir: css

integration_spreadsheet_key: 10gcRgtFZyJAm3g02xMt8GuzTXCDzdEwoJEqD3Uiz9To

defaults:
  - scope:
      path: "assets/gallery"
    values:
      image: true