# GC50 Website Trial

title: GC50 Virtual Challenge
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  GC50 Virtual Challenge
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gc50vc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  gc50vc
github_repo: ''

plugins:
- jekyll-feed

sass:
    sass_dir: css

integration_spreadsheet_key: 1P_eKRABIs7vQG0-p7Z8ElE_EpCOJl3bEJ8gUH5ScEHU

defaults:
  - scope:
      path: "assets/gallery"
    values:
      image: true
